export const productCategories = ["Roti", "Kue", "Makanan Berat", "Snack", "Dessert", "Minuman"];

export const sampleProducts = [
  {
    id: "roti-cokelat",
    name: "Roti Cokelat",
    category: "Roti",
    price: 12000,
    remealPrice: 8000,
    stock: 8,
    condition: "Dibuat hari ini",
    status: "Segera Berakhir",
    createdAt: "2 Okt 2026",
    endsAt: "19.30 hari ini",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=240&q=80",
    description: "Roti lembut isi cokelat, dibuat pagi ini. Stok surplus menjelang toko tutup.",
  },
  {
    id: "croissant-mentega",
    name: "Croissant Mentega",
    category: "Roti",
    price: 18000,
    remealPrice: 12000,
    stock: 6,
    condition: "Dibuat hari ini",
    status: "Tersedia",
    createdAt: "2 Okt 2026",
    endsAt: "20.00 hari ini",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=240&q=80",
    description: "Croissant renyah berlapis, dipanggang pagi ini. Cocok untuk teman minum kopi.",
  },
  {
    id: "donat-cokelat",
    name: "Donat Cokelat",
    category: "Snack",
    price: 10000,
    remealPrice: 7000,
    stock: 10,
    condition: "Dibuat hari ini",
    status: "Tersedia",
    createdAt: "2 Okt 2026",
    endsAt: "19.00 hari ini",
    image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=240&q=80",
    description: "Donat empuk dengan topping cokelat, dibuat segar hari ini. Harga spesial untuk stok sore.",
  },
  {
    id: "brownies-potong",
    name: "Brownies Cokelat (4 potong)",
    category: "Kue",
    price: 28000,
    remealPrice: 19000,
    stock: 0,
    condition: "Dibuat hari ini",
    status: "Habis",
    createdAt: "2 Okt 2026",
    endsAt: "18.30 hari ini",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=240&q=80",
    description: "Brownies fudgy potongan hari ini. Stok sudah habis.",
  },
  {
    id: "risoles-mayo",
    name: "Risoles Mayo (3 pcs)",
    category: "Snack",
    price: 24000,
    remealPrice: 16000,
    stock: 5,
    condition: "Siap santap",
    status: "Tersedia",
    createdAt: "2 Okt 2026",
    endsAt: "19.30 hari ini",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=240&q=80",
    description: "Risoles isi smoked beef dan mayo, digoreng sore ini. Simpan dalam kemasan tertutup.",
  },
  {
    id: "nasi-ayam",
    name: "Nasi Ayam Sambal Matah",
    category: "Makanan Berat",
    price: 32000,
    remealPrice: 22000,
    stock: 2,
    condition: "Siap santap",
    status: "Penjualan Ditutup",
    createdAt: "2 Okt 2026",
    endsAt: "18.00 hari ini",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=240&q=80",
    description: "Nasi dengan ayam dan sambal matah. Penjualan hari ini sudah ditutup.",
  },
  {
    id: "rice-bowl-ayam",
    name: "Rice Bowl Ayam Teriyaki",
    category: "Makanan Berat",
    price: 30000,
    remealPrice: 21000,
    stock: 4,
    condition: "Siap santap",
    status: "Segera Berakhir",
    createdAt: "2 Okt 2026",
    endsAt: "19.00 hari ini",
    image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=240&q=80",
    description: "Rice bowl ayam teriyaki dengan sayuran. Dibuat siang ini, ambil sebelum tutup.",
  },
  {
    id: "salad-buah",
    name: "Salad Buah Yogurt",
    category: "Dessert",
    price: 25000,
    remealPrice: 17000,
    stock: 3,
    condition: "Disimpan dingin",
    status: "Tersedia",
    createdAt: "2 Okt 2026",
    endsAt: "20.00 hari ini",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=240&q=80",
    description: "Potongan buah segar dengan saus yogurt, selalu disimpan dalam lemari pendingin.",
  },
  {
    id: "es-kopi-susu",
    name: "Es Kopi Susu Gula Aren",
    category: "Minuman",
    price: 22000,
    remealPrice: 15000,
    stock: 7,
    condition: "Dibuat hari ini",
    status: "Tersedia",
    createdAt: "2 Okt 2026",
    endsAt: "20.30 hari ini",
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=240&q=80",
    description: "Kopi susu dengan gula aren, dibuat hari ini dan disajikan dingin.",
  },
];

export function formatPrice(value) {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    maximumFractionDigits: 0,
  }).format(value);
}